name: todo_app_ga
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sembast: ^3.7.5
  path_provider: ^2.1.4
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0


flutter:
  uses-material-design: true